version: "3.9"

services:
 postgres:
    image: postgres:latest
    container_name: postgres_api
    restart: always
    ports:
      - 5432:5432
    environment:
     - POSTGRES_PASSWORD=123
     - POSTGRES_USER=postgres
     - POSTGRES_DB=postgres
    # - PGDATA=/var/lib/postgresql/data/pgdata
    networks:
      - database
 lib:
    restart: on-failure
    container_name: main_api
    build: ./
    # entrypoint: dart run /app/bin/conduittest.dart conduit:conduit
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=123
      - DB_HOST=postgres_api
      - DB_PORT=5432
      - DB_NAME=postgres
      - SECRET_KEY=SECRET_KEY
    depends_on:
      - postgres
    ports:
      - 8888:8888
    networks:
      - database
volumes:
  dart_api:

networks:
  database: